import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header"; // Corrected path
import AppProvider from '../components/AppContext.js';
import { Toaster } from "react-hot-toast";
const robo = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Food Ordering Web App",
  description: "Generated by create next app",
  
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={robo.className}>
        <main className="max-w-4xl mx-auto py-4">
         <AppProvider>
          <Toaster/>
          <Header />
          {children}
          <footer className="border-t p-8 text-center text-gray-500 mt-16">
            &copy; 2024 All rights reserved
          </footer>
         </AppProvider>
        </main>
      </body>
    </html>
  );
}
